// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: stakeholdersMicroservice.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StakeholdersMicroserviceClient is the client API for StakeholdersMicroservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StakeholdersMicroserviceClient interface {
	GenerateAccessToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type stakeholdersMicroserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewStakeholdersMicroserviceClient(cc grpc.ClientConnInterface) StakeholdersMicroserviceClient {
	return &stakeholdersMicroserviceClient{cc}
}

func (c *stakeholdersMicroserviceClient) GenerateAccessToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/server.StakeholdersMicroservice/GenerateAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakeholdersMicroserviceServer is the server API for StakeholdersMicroservice service.
// All implementations must embed UnimplementedStakeholdersMicroserviceServer
// for forward compatibility
type StakeholdersMicroserviceServer interface {
	GenerateAccessToken(context.Context, *TokenRequest) (*TokenResponse, error)
	mustEmbedUnimplementedStakeholdersMicroserviceServer()
}

// UnimplementedStakeholdersMicroserviceServer must be embedded to have forward compatible implementations.
type UnimplementedStakeholdersMicroserviceServer struct {
}

func (UnimplementedStakeholdersMicroserviceServer) GenerateAccessToken(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessToken not implemented")
}
func (UnimplementedStakeholdersMicroserviceServer) mustEmbedUnimplementedStakeholdersMicroserviceServer() {
}

// UnsafeStakeholdersMicroserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StakeholdersMicroserviceServer will
// result in compilation errors.
type UnsafeStakeholdersMicroserviceServer interface {
	mustEmbedUnimplementedStakeholdersMicroserviceServer()
}

func RegisterStakeholdersMicroserviceServer(s grpc.ServiceRegistrar, srv StakeholdersMicroserviceServer) {
	s.RegisterService(&StakeholdersMicroservice_ServiceDesc, srv)
}

func _StakeholdersMicroservice_GenerateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholdersMicroserviceServer).GenerateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.StakeholdersMicroservice/GenerateAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholdersMicroserviceServer).GenerateAccessToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StakeholdersMicroservice_ServiceDesc is the grpc.ServiceDesc for StakeholdersMicroservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StakeholdersMicroservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StakeholdersMicroservice",
	HandlerType: (*StakeholdersMicroserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAccessToken",
			Handler:    _StakeholdersMicroservice_GenerateAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stakeholdersMicroservice.proto",
}
